### ISSUE TITLE
FTP sync broken

### ISSUE THREAD

**Issue by benhylau** [starlinglab/starling-integrity-api#36]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Fix ftp sync.  

FTP sync stopped working and manual run has it crashing with:

```
starling@lab1:/mnt/volume_tor1_01/starling/sftp$ /usr/bin/python3 /usr/local/bin/pyftpsync sync --no-prompt --no-keyring --no-verify-host-keys --resolve=skip /mnt/volume_tor1_01/starling/sftp sftp://47.89.10.4
Synchronize /mnt/volume_tor1_01/starling/sftp
                with sftp://47.89.10.4/
Encoding local: utf-8, remote: utf-8
Connecting None:*** to sftp://47.89.10.4
Using credentials from .netrc file: starling_sync:***.
Could not remove lock file: [Errno 2] No such file
Could not remove lock file: [Errno 2] No such file
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/pyftpsync.py", line 251, in run
    s.run()
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/synchronizers.py", line 833, in run
    res = super(BiDirSynchronizer, self).run()
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/synchronizers.py", line 213, in run
    self.close()
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/synchronizers.py", line 163, in close
    self.remote.close()
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/sftp_target.py", line 211, in close
    self._unlock(closing=True)
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/sftp_target.py", line 262, in _unlock
    self.sftp.remove(DirMetadata.LOCK_FILE_NAME)
  File "/usr/local/lib/python3.9/dist-packages/pysftp/__init__.py", line 728, in remove
    self._sftp.remove(remotefile)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 398, in remove
    self._request(CMD_REMOVE, path)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 903, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyftpsync", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/pyftpsync.py", line 258, in run
    s.remote.close()
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/sftp_target.py", line 211, in close
    self._unlock(closing=True)
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/sftp_target.py", line 262, in _unlock
    self.sftp.remove(DirMetadata.LOCK_FILE_NAME)
  File "/usr/local/lib/python3.9/dist-packages/pysftp/__init__.py", line 728, in remove
    self._sftp.remove(remotefile)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 398, in remove
    self._request(CMD_REMOVE, path)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 903, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Exception ignored in: <function BaseSynchronizer.__del__ at 0x7fc4055773a0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/synchronizers.py", line 154, in __del__
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/synchronizers.py", line 163, in close
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/sftp_target.py", line 211, in close
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/sftp_target.py", line 267, in _unlock
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _Target.__del__ at 0x7fc40556ba60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/targets.py", line 134, in __del__
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/sftp_target.py", line 211, in close
  File "/usr/local/lib/python3.9/dist-packages/ftpsync/sftp_target.py", line 267, in _unlock
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Connection.__del__ at 0x7fc4044dd940>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pysftp/__init__.py", line 1013, in __del__
  File "/usr/local/lib/python3.9/dist-packages/pysftp/__init__.py", line 785, in close
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 195, in close
  File "/usr/local/lib/python3.9/dist-packages/paramiko/channel.py", line 671, in close
  File "/usr/local/lib/python3.9/dist-packages/paramiko/transport.py", line 1846, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'
```

## To Do

- [ ] ...

**Comment by benhylau** [comment]
Okay this seems to be due to the partial wiping of FTP sync management files. It didn't happen again and the system has been reliable. Closing.
