### ISSUE TITLE
Make sure server starts up on Mac OS

### ISSUE THREAD

**Issue by anaulin** [starlinglab/starling-integrity-api#60]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** `pipenv run server` succeeds on Mac OS; timebox work -- abandon this if it is turns out to be Too Hard ™️ 

Ben ran into this issue on his local machine:
```
❯❯❯ pipenv run server                                                                                      main
Loading .env environment variables...
Loaded configuration for organizations: dict_keys(['hyphacoop'])
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/internal/hyphacoop/assets already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/internal/hyphacoop/claims already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/internal/hyphacoop/tmp already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/internal/hyphacoop/create already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/internal/hyphacoop/create-proofmode already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/add already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/update already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/store already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/custom already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/create-output already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/create-proofmode-output already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/add-output already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/update-output already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/store-output already exists
[2022-02-18T02:13:26-0500] {file_util.py:31} INFO: Directory /Users/benedict/.starling-integrity/fs/hyphacoop/custom-output already exists
Traceback (most recent call last):
  File "/Users/benedict/Dev/starling/starling-integrity-api/main.py", line 102, in <module>
    proc.start()
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x1041b0040>: attribute lookup <lambda> on __main__ failed
```

## To Do

- [ ] Reproduce issue locally
- [ ] Make fix

**Comment by anaulin** [comment]
@benhylau closing this as fixed, but do feel free to reopen if you find that you are still running into issues
